name: Run E2E Tests

on:
  workflow_run:
    workflows: ["Run Unit Tests"]
    types:
      - completed

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run services
        run: |
          docker compose -f test.compose.yaml up --build -d --scale e2e=0
          
      - name: Wait for services
        run: |
          sleep 10  # Adjust as needed for your services to be ready

      - name: Run E2E tests
        run: |
          docker compose -f test.compose.yaml run --rm e2e          

      - name: Shut down services
        run: docker compose -f test.compose.yaml down --volumes
