name: Run Unit Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.0

      - name: Build and run tests
        working-directory: ./movies-api
        run: |
          docker build --target test -t movies-api-test .
          docker run movies-api-test
